[workspace]
resolver = "2"
members = [
    "rates-exporter",
    "rates-api",
]

[workspace.dependencies]
async-trait = "0.1.73"
mongodb = "3.0.1"
config = "0.14.0"
dotenvy = "0.15.7"
tokio = { version = "1.33.0", features = ["full"] }
serde = { version = "1.0.207", features = ["derive"] }