[graph]
all-features = false
no-default-features = false

[output]
feature-depth = 1

[advisories]
ignore = ["RUSTSEC-2024-0320"] # https://rustsec.org/packages/yaml-rust.html

[licenses]
confidence-threshold = 0.8
allow = [
    "MIT",
    "BSD-3-Clause",
    "ISC",
    "Apache-2.0",
    "MPL-2.0",
    "Unicode-DFS-2016",
    "CC0-1.0",
    "OpenSSL",
]

[[licenses.clarify]]
name = "ring"
expression = "ISC AND MIT AND OpenSSL"
license-files = [{ path = "LICENSE", hash = 0xbd0eed23 }]

[bans]
multiple-versions = "warn"
wildcards = "deny"
highlight = "all"
workspace-default-features = "allow"
external-default-features = "allow"

[sources]
unknown-registry = "warn"
unknown-git = "warn"
allow-registry = ["https://github.com/rust-lang/crates.io-index"]
