services:
  rates-exporter:
    build:
      context: .
      dockerfile: rates-exporter/Dockerfile
    hostname: rates-exporter
    container_name: rates-exporter
    image: rates-exporter:latest
    depends_on:
      - mongo
    environment:
      - RATES_EXPORTER__DATABASE__DB_NAME=coin-board
      - RATES_EXPORTER__DATABASE__URI=mongodb://mongo:27017/coin-board
      - RATES_EXPORTER__PROVIDER__URI=https://api.coingecko.com/api/v3/coins/markets
      - RATES_EXPORTER__PROVIDER__COINS=bitcoin,ethereum,solana,dogecoin,the-open-network,binancecoin,ripple,pepe,sun-token,litecoin,shiba-inu,nyan-meme-coin
      - RUST_BACKTRACE=1
      - RUST_LOG=debug

  rates-api:
    build:
      context: .
      dockerfile: rates-api/Dockerfile
    hostname: rates-api
    container_name: rates-api
    image: rates-api:latest
    depends_on:
      - mongo
    ports:
      - "7373:7373"
      - "5000:5000"
    environment:
      - RATES_API__ENDPOINTS__HOST=0.0.0.0
      - RATES_API__ENDPOINTS__PORT=7373
      - RATES_API__METRICS__HOST=0.0.0.0
      - RATES_API__METRICS__PORT=5000
      - RATES_API__DATABASE__DB_NAME=coin-board
      - RATES_API__DATABASE__URI=mongodb://mongo:27017/coin-board
      - RATES_API__CORS__METHODS=GET
      - RATES_API__CORS__HEADERS=User-Agent
      - RATES_API__CORS__ORIGIN=http://localhost:3000
      - RATES_API__CORS__MAX_AGE=3600
      - RUST_BACKTRACE=1
      - RUST_LOG=debug

  mongo:
    hostname: mongo
    container_name: mongo
    image: mongo:7.0
    ports:
      - "27017:27017"