imagePullSecrets: github-registry
namespace: coin-board

ui:
  backendUri: http://localhost:7373
  externalPort: 80
  internalPort: 3000
  replicas: 1
  weight: 4
  label: coin-board-ui
  image:
    name: ghcr.io/rdcm/coin-board-ui/coin-board-ui
    tag: v1.0.3
  resources:
    limits:
      memory: "512Mi"
      cpu: "250m"

mongodb:
  label: mongodb
  replicas: 1
  weight: 2
  port: 27017
  image:
    name: mongo
    tag: latest
  resources:
    requests:
      memory: "256Mi"
      cpu: "250m"
    limits:
      memory: "512Mi"
      cpu: "500m"
  volume:
    capacity: 1000Mi

exporter:
  db:
    uri: mongodb://mongodb-service:27017/coin-board
    name: coin-board
  provider:
    uri: https://api.coingecko.com/api/v3/coins/markets
    coins: bitcoin,ethereum,solana,dogecoin,the-open-network,binancecoin,ripple,pepe,sun-token,litecoin,shiba-inu,nyan-meme-coin
  label: rates-exporter
  expression: "*/5 * * * *" # every 5 minutes
  failedJobsHistoryLimit: 3
  successfulJobsHistoryLimit: 3
  concurrencyPolicy: Forbid
  replicas: 1
  weight: 3
  image:
    name: ghcr.io/rdcm/coin-board/rates-exporter
    tag: v1.0.3
  pullPolicy: Never
  resources:
    limits:
      memory: "128Mi"
      cpu: "50m"

api:
  label: rates-api
  replicas: 1
  weight: 4
  host: 0.0.0.0
  externalPort: 80
  internalPort: 7373
  metrics:
    host: 0.0.0.0
    port: 5000
  image:
    name: ghcr.io/rdcm/coin-board/rates-api
    tag: v1.0.3
  resources:
    limits:
      memory: "128Mi"
      cpu: "50m"
  ingress:
    ingressClassName: nginx
  mongodb:
    uri: mongodb://mongodb-service:27017/
    dbName: coin-board
  cors:
    methods: GET
    headers: User-Agent
    origin: http://localhost:3000
    maxAge: 3600