apiVersion: batch/v1
kind: CronJob
metadata:
  namespace: {{ .Values.namespace }}
  name: {{ .Values.exporter.name }}-cronjob
spec:
  schedule: "{{ .Values.exporter.expression }}"
  failedJobsHistoryLimit: {{ .Values.exporter.failedJobsHistoryLimit }}
  successfulJobsHistoryLimit: {{ .Values.exporter.successfulJobsHistoryLimit }}
  concurrencyPolicy: {{ .Values.exporter.concurrencyPolicy }}
  jobTemplate:
    spec:
      template:
        spec:
          imagePullSecrets:
            - name: {{ .Values.imagePullSecrets }}
          containers:
            - name: {{ .Values.exporter.name }}
              image: "{{ .Values.exporter.image.name }}:{{ .Values.exporter.image.tag }}"
              resources:
                requests:
                  memory: {{ .Values.exporter.resources.requests.memory }}
                  cpu: {{ .Values.exporter.resources.requests.cpu }}
                limits:
                  memory: {{ .Values.exporter.resources.limits.memory }}
                  cpu: {{ .Values.exporter.resources.limits.cpu }}
              envFrom:
                - configMapRef:
                    name: {{ .Values.exporter.name }}-config
          restartPolicy: OnFailure