apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.mongodb.label }}-service
  labels:
    app: {{ .Values.mongodb.label }}
spec:
  ports:
    - port: {{ .Values.mongodb.port }}
      targetPort: {{ .Values.mongodb.port }}
  selector:
    app: {{ .Values.mongodb.label }}
  clusterIP: None  # Headless service for StatefulSet
