apiVersion: v1
kind: ConfigMap
metadata:
  namespace: {{ .Values.namespace }}
  name: {{ .Values.ui.name }}-config
  labels:
    app: {{ .Values.ui.name }}
data:
  COIN_BOARD_UI_API_URL: "{{ .Values.ui.backendUri }}"