apiVersion: apps/v1
kind: Deployment
metadata:
  namespace: {{ .Values.namespace }}
  name: {{ .Values.ui.name }}-deployment
  annotations:
    "helm.sh/hook-weight": "{{ .Values.ui.weight }}"
spec:
  replicas: {{ .Values.ui.replicas }}
  selector:
    matchLabels:
      app: {{ .Values.ui.name }}
  template:
    metadata:
      labels:
        app: {{ .Values.ui.name }}
    spec:
      imagePullSecrets:
        - name: {{ .Values.imagePullSecrets }}
      containers:
        - name: {{ .Values.ui.name }}
          image: "{{ .Values.ui.image.name }}:{{ .Values.ui.image.tag }}"
          envFrom:
            - configMapRef:
                name: {{ .Values.ui.name }}-config
          resources:
            limits:
              memory: {{ .Values.ui.resources.limits.memory }}
              cpu: {{ .Values.ui.resources.limits.cpu }}
          ports:
            - containerPort: {{ .Values.ui.internalPort }}