apiVersion: v1
kind: Service
metadata:
  namespace: {{ .Values.namespace }}
  name: {{ .Values.ui.name }}-service
spec:
  selector:
    app: {{ .Values.ui.name }}
  ports:
    - protocol: TCP
      port: {{ .Values.ui.externalPort }}
      targetPort: {{ .Values.ui.internalPort }}
  type: ClusterIP