apiVersion: v1
kind: Service
metadata:
  namespace: {{ .Values.namespace }}
  name: {{ .Values.ui.label }}-service
spec:
  selector:
    app: {{ .Values.ui.label }}
  ports:
    - protocol: TCP
      port: {{ .Values.ui.externalPort }}
      targetPort: {{ .Values.ui.internalPort }}
  type: ClusterIP