namespace: monitoring
storageClassName: hostpath

grafana:
  name: grafana
  port: 3000
  replicas: 1
  image:
    name: grafana/grafana
    tag: latest
  storageCapacity: 1Gi

prometheus:
  name: prometheus
  port: 9090
  replicas: 1
  image:
    name: prom/prometheus
    tag: v2.42.0
  storageCapacity: 1Gi

loki:
  name: loki
  port: 3100
  replicas: 1
  image:
    name: grafana/loki
    tag: 3.1.1
  configsVolume: config
  storageCapacity: 1Gi

promtail:
  name: promtail
  image:
    name: grafana/promtail
    tag: 3.1.1
  configsVolume: config
  containersVolume: containers
  logsVolume: logs