namespace: monitoring

grafana:
  name: grafana
  port: 3000
  replicas: 1
  image:
    name: grafana/grafana
    tag: latest
  resources:
    requests:
      memory: "128Mi"
      cpu: "50m"
    limits:
      memory: "256Mi"
      cpu: "100m"
  storageCapacity: 1Gi

prometheus:
  name: prometheus
  port: 9090
  replicas: 1
  image:
    name: prom/prometheus
    tag: v2.42.0
  resources:
    requests:
      memory: "128Mi"
      cpu: "50m"
    limits:
      memory: "256Mi"
      cpu: "100m"
  storageCapacity: 1Gi