apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Values.api.label }}-deployment
  annotations:
    "helm.sh/hook-weight": "{{ .Values.api.weight }}"
spec:
  selector:
    matchLabels:
      app: {{ .Values.api.label }}
  template:
    metadata:
      labels:
        app: {{ .Values.api.label }}
    spec:
      imagePullSecrets:
        - name: {{ .Values.imagePullSecrets }}
      containers:
        - name: {{ .Values.api.label }}
          image: "{{ .Values.api.image.name }}:{{ .Values.api.image.tag }}"
          env:
            - name: RATES_API__DATABASE__URI
              value: {{ .Values.api.mongodb.uri }}
            - name: RATES_API__DATABASE__DB_NAME
              value: {{ .Values.api.mongodb.dbName }}
            - name: RATES_API__CORS__METHODS
              value: {{ .Values.api.cors.methods }}
            - name: RATES_API__CORS__HEADERS
              value: {{ .Values.api.cors.headers }}
            - name: RATES_API__CORS__ORIGIN
              value: {{ .Values.api.cors.origin }}
            - name: RATES_API__CORS__MAX_AGE
              value: "{{ .Values.api.cors.maxAge }}"
            - name: RATES_API__ENDPOINTS__HOST
              value: {{ .Values.api.host }}
            - name: RATES_API__ENDPOINTS__PORT
              value: "{{ .Values.api.port }}"
          resources:
            limits:
              memory: {{ .Values.api.resources.limits.memory }}
              cpu: {{ .Values.api.resources.limits.cpu }}
          ports:
            - containerPort: {{ .Values.api.port }}