apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: {{ .Values.api.label }}-ingress
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: /
    {{- if eq .Values.env "prod" }}
    {{- with .Values.ingress.annotations }}
    {{- toYaml . | nindent 4 }}
    {{- end }}
    {{- end }}
spec:
  ingressClassName: nginx
  tls:
    - hosts:
        - {{ .Values.api.ingress.host }}
      secretName: {{ .Values.api.label }}-tls
  rules:
    - host: {{ .Values.api.ingress.host }}
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: {{ .Values.api.label }}-service
                port:
                  number: 80