apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .Values.loki.name }}-config
  namespace: {{ .Values.namespace }}
data:
  loki-config.yaml: |
{{ .Files.Get "configs/loki/loki-config.yaml" | indent 4 }}
