apiVersion: apps/v1
kind: Deployment
metadata:
  namespace: {{ .Values.namespace }}
  name: {{ .Values.api.label }}-deployment
  annotations:
    "helm.sh/hook-weight": "{{ .Values.api.weight }}"
spec:
  replicas: {{ .Values.api.replicas }}
  selector:
    matchLabels:
      app: {{ .Values.api.label }}
  template:
    metadata:
      annotations:
        prometheus.io/scrape: "true"
        prometheus.io/path: "/metrics"
        prometheus.io/port: "5000"
      labels:
        app: {{ .Values.api.label }}
    spec:
      imagePullSecrets:
        - name: {{ .Values.imagePullSecrets }}
      containers:
        - name: {{ .Values.api.label }}
          image: "{{ .Values.api.image.name }}:{{ .Values.api.image.tag }}"
          envFrom:
            - configMapRef:
                name: {{ .Values.api.label }}-config
          resources:
            limits:
              memory: {{ .Values.api.resources.limits.memory }}
              cpu: {{ .Values.api.resources.limits.cpu }}
          ports:
            - containerPort: {{ .Values.api.internalPort }}