# http://localhost:3000/api/datasources
apiVersion: 1
datasources:
  - name: prometheus
    type: prometheus
    uid: fdww6u6ehb0g0d
    orgId: 1
    typeName: Prometheus
    access: proxy
    url: http://prometheus-service:9090
    typeLogoUrl: public/app/plugins/datasource/prometheus/img/prometheus_logo.svg
    jsonData:
      httpMethod: POST
    readOnly: false
    isDefault: true
  - name: loki
    type: loki
    uid: ddxdvdy3mxse8f
    orgId: 1
    typeName: Loki
    access: proxy
    url: http://loki-service:3100
    typeLogoUrl: public/app/plugins/datasource/loki/img/loki_icon.svg
    readOnly: false
    isDefault: false