apiVersion: v2
name: coin-board
description: coin-board
type: application
version: 0.1.0
appVersion: "1.16.0"
dependencies:
  - name: ingress-nginx
    version: "4.8.3"
    repository: "https://kubernetes.github.io/ingress-nginx"