imagePullSecrets: github-registry

ui:
  backendUri: http://localhost:7373
  externalPort: 80
  internalPort: 3000
  replicas: 1
  weight: 4
  label: coin-board-ui
  image:
    name: ghcr.io/rdcm/coin-board-ui/coin-board-ui
    tag: latest
  resources:
    limits:
      memory: "512Mi"
      cpu: "250m"

mongodb:
  label: mongodb
  replicas: 1
  weight: 2
  port: 27017
  image:
    name: mongo
    tag: latest
  resources:
    limits:
      memory: "512Mi"
      cpu: "50m"
  volume:
    capacity: 1000Mi

exporter:
  db:
    uri: mongodb://mongodb-service:27017/coin-board
    name: coin-board
  provider:
    uri: https://api.coingecko.com/api/v3/coins/markets
    fetchDelay: 10000
    pageSize: 250
  label: rates-exporter
  expression: "*/15 * * * *"
  replicas: 1
  weight: 3
  image:
    name: ghcr.io/rdcm/coin-board/rates-exporter
    tag: latest
  pullPolicy: Never
  resources:
    limits:
      memory: "128Mi"
      cpu: "50m"

api:
  label: rates-api
  replicas: 1
  weight: 4
  host: 0.0.0.0
  externalPort: 80
  internalPort: 7373
  image:
    name: ghcr.io/rdcm/coin-board/rates-api
    tag: latest
  resources:
    limits:
      memory: "128Mi"
      cpu: "50m"
  ingress:
    ingressClassName: nginx
  mongodb:
    uri: mongodb://mongodb-service:27017/
    dbName: coin-board
  cors:
    methods: GET
    headers: User-Agent
    origin: http://localhost:3000
    maxAge: 3600