apiVersion: apps/v1
kind: StatefulSet
metadata:
  namespace: {{ .Values.namespace }}
  name: {{ .Values.mongodb.label }}-stateful-set
  labels:
    app: {{ .Values.mongodb.label }}
spec:
  serviceName: "mongodb"
  replicas: 1  # Start with 1 replica, can be scaled up later
  selector:
    matchLabels:
      app: {{ .Values.mongodb.label }}
  template:
    metadata:
      labels:
        app: {{ .Values.mongodb.label }}
    spec:
      containers:
        - name: {{ .Values.mongodb.label }}
          image: "{{ .Values.mongodb.image.name }}:{{ .Values.mongodb.image.tag }}"
          ports:
            - containerPort: {{ .Values.mongodb.port }}
          volumeMounts:
            - name: {{ .Values.mongodb.label }}-data
              mountPath: /data/db
          resources:
            requests:
              memory: {{ .Values.mongodb.resources.requests.memory }}
              cpu: {{ .Values.mongodb.resources.requests.cpu }}
            limits:
              memory: {{ .Values.mongodb.resources.limits.memory }}
              cpu: {{ .Values.mongodb.resources.limits.cpu }}
  volumeClaimTemplates:
    - metadata:
        name: {{ .Values.mongodb.label }}-data
      spec:
        accessModes: [ "ReadWriteOnce" ]
        resources:
          requests:
            storage: {{ .Values.mongodb.volume.capacity }}
        storageClassName: {{ .Values.mongodb.storageClassName }}
