apiVersion: batch/v1
kind: CronJob
metadata:
  name: {{ .Values.exporter.label }}
spec:
  schedule: "{{ .Values.exporter.expression }}"
  failedJobsHistoryLimit: {{ .Values.exporter.failedJobsHistoryLimit }}
  successfulJobsHistoryLimit: {{ .Values.exporter.successfulJobsHistoryLimit }}
  concurrencyPolicy: {{ .Values.exporter.concurrencyPolicy }}
  jobTemplate:
    spec:
      template:
        spec:
          imagePullSecrets:
            - name: {{ .Values.imagePullSecrets }}
          containers:
            - name: {{ .Values.exporter.label }}
              image: "{{ .Values.exporter.image.name }}:{{ .Values.exporter.image.tag }}"
              envFrom:
                - configMapRef:
                    name: {{ .Values.exporter.label }}-config
          restartPolicy: OnFailure