apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .Values.prometheus.name }}-config
  namespace: {{ .Values.namespace }}
data:
  prometheus.yaml: |
{{ .Files.Get "configs/prometheus/prometheus.yaml" | indent 4 }}
