apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ .Values.prometheus.name }}-service-account
  namespace: {{ .Values.namespace }}
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: {{ .Values.prometheus.name }}-cluster-role
rules:
  - apiGroups: [""]
    resources: ["pods", "services", "endpoints", "nodes", "nodes/proxy"]
    verbs: ["get", "list", "watch"]
  - apiGroups: ["extensions"]
    resources: ["ingresses"]
    verbs: ["get", "list", "watch"]
  - apiGroups:
      - "networking.k8s.io"
    resources:
      - networkpolicies
    verbs: ["get", "list", "watch"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: {{ .Values.prometheus.name }}-cluster-role-binding
subjects:
  - kind: ServiceAccount
    name: {{ .Values.prometheus.name }}-service-account
    namespace: {{ .Values.namespace }}
roleRef:
  kind: ClusterRole
  name: {{ .Values.prometheus.name }}-cluster-role
  apiGroup: rbac.authorization.k8s.io
