name: Build and Publish Docker Images

on:
  push:
    tags:
      - 'v*.*.*'

jobs:
  build-and-push:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Log in to GitHub Container Registry
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GHCR_TOKEN }}

      - name: Extract version from tag
        id: extract_tag
        run: echo "TAG_VERSION=${GITHUB_REF#refs/tags/}" >> $GITHUB_ENV

      - name: Build and push rates-api image
        run: |
          docker buildx build --push --tag ghcr.io/${{ github.repository }}/rates-api:${{ env.TAG_VERSION }} -f rates-api/Dockerfile .

      - name: Build and push rates-exporter image
        run: |
          docker buildx build --push --tag ghcr.io/${{ github.repository }}/rates-exporter:${{ env.TAG_VERSION }} -f rates-exporter/Dockerfile .