name: Build and Publish Docker Images

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build-and-push:
    runs-on: ubuntu-latest

    steps:
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Log in to GitHub Container Registry
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GHCR_TOKEN }}

      - name: Build and push rates-api image
        run: |
          docker buildx build --push --tag ghcr.io/${{ github.repository }}/rates-api:latest -f rates-api/Dockerfile .

      - name: Build and push rates-exporter image
        run: |
          docker buildx build --push --tag ghcr.io/${{ github.repository }}/rates-exporter:latest -f rates-exporter/Dockerfile .
